### ISSUE TITLE
Bumping dependencies breaks clean install from old EPD

### ISSUE THREAD

**Issue by corranwebster** [enthought/ets#1]
The most recent check-in bumped dependencies to things like traits 4 - the ETS 4 packages.  When doing the standard ets development procedure for a fresh install, this breaks things, since the only easy way to get the updated versions of these right now is by installing ets.py, but you can't, because...

ie. the following fails

git clone ...
cd ets
python setup.py install

There is a work-around of just running the ets.py script directly to do the initial checkout of the ETS 4 packages, but having the ets package depending on the very things you are trying to get seems wrong.  This is also temporary until the next version of EPD comes out, but still it seems sub-optimal.

Do we actually need the dependencies on things like traits for the ets project?

**Comment by mdickinson** [comment]
@corranwebster Close this as out of date?
