### ISSUE TITLE
Don't test against Mac OS on Travis CI

### ISSUE THREAD

**Issue by rahulporuri** [enthought/ets#52]
Given the recent pricing plan changes for Travis CI, testing against Mac OS on Travis CI is no longer a possibility for ETS projects. While we find an alternative, we need to turn off Mac OS testing for all ETS projects on Travis CI.

- [x] traits (Mac OS builds run on GitHub Actions CI, not Travis CI, nothing to do.)
- [x] pyface (https://github.com/enthought/pyface/pull/820)
- [x] traitsui (Mac OS builds run on Appveyor CI, not Travis CI, nothing to do)
- [x] envisage (https://github.com/enthought/envisage/pull/375)
- [x] traits-futures (https://github.com/enthought/traits-futures/pull/267)
- [x] enable (No MacOS builds, nothing to do)
- [x] chaco (https://github.com/enthought/chaco/pull/543)
- [x] mayavi (https://github.com/enthought/mayavi/pull/982)
- [x] ets-copyright-checker (https://github.com/enthought/ets-copyright-checker/pull/19)
- [x] scimath (https://github.com/enthought/scimath/pull/97)
- [x] graphcanvas (https://github.com/enthought/graphcanvas/pull/25)
- [x] codetools (https://github.com/enthought/codetools/pull/46)
- [x] qt_binder (https://github.com/enthought/qt_binder/pull/64)

See related #53

**Comment by rahulporuri** [comment]
closing now that all active projects have been updated to not test against Mac OS on Travis CI.

**Comment by mdickinson** [comment]
Some other open source repositories with semi-recent history:

- traits_enaml: no macOS builds; nothing to do
- pyql: no macOS builds; nothing to do
- ibm2ieee: no macOS builds; nothing to do
- sectiondoc: no macOS builds; nothing to do
- trait_documenter: ditto
- sat-solver: ditto
- okonomiyaki: ditto
- hatcher: ditto
