### ISSUE TITLE
Re-enable CI against Mac OS

### ISSUE THREAD

**Issue by rahulporuri** [enthought/ets#53]
Now that we need to move away from testing against Mac OS on Travis CI, we need to evaluate what CI provider to use to test against Mac OS for the various ETS projects.

A short term option is to move the Mac OS jobs to Appveyor CI.
A longer term option is to move the Mac OS job sto GitHub Actions CI but that requires setting up GitHub Actions CI for a number of ETS projects.

See related https://github.com/enthought/ets/issues/52

**Comment by mdickinson** [comment]
I think setting up GitHub Actions is easy enough that we should just do that, rather than migrating the macOS jobs to Appveyor. A big advantage is that we then get to eliminate the Travis CI (and Appveyor) configurations entirely.

**Comment by kitchoi** [comment]
enable now has CI against Mac OS on GitHub Actions: https://github.com/enthought/enable/pull/538

**Comment by rahulporuri** [comment]
closing as we have migrated all ETS projects to use GitHub Actions CI - and Mac OS testing is happening via GitHub Actions CI now.
