### ISSUE TITLE
Normalize CI across projects - GH Actions

### ISSUE THREAD

**Issue by aaronayres35** [enthought/ets#63]
Over the course of the past two quarters, we have slowly moved ETS projects from using Travis CI and Appveyor CI to also using GitHub Actions CI. The end goal here was to move away from Travis CI but because GitHub Actions CI also makes it possible to test on Windows, we should be able to move away from Appveyor CI as well.

Some ETS projects have already moved away from both Travis and Appveyor CI but in some cases, Appveyor CI is still used. This needs to be audited and rectified.

**Comment by rahulporuri** [comment]
Projects which use Appveyor CI 
- [x] pyface
- [x] traitsui
- [x] envisage
- [x] apptools
- [x] scimath
- [x] chaco

Appveyor CI can be removed from the aforementioned projects.

Projects which only rely on GitHub Actions CI
- traits
- traits-futures
- enable

**Comment by rahulporuri** [comment]
closing as all items have been completed.
