### ISSUE TITLE
Make it possible to manually trigger all ETS cron jobs

### ISSUE THREAD

**Issue by rahulporuri** [enthought/ets#68]
At the moment, some cron jobs can be manually triggered and some cannot be. It would be nice if we made it possible to manually trigger all ETS cron jobs - using `workflow_dispatch`.

**Comment by rahulporuri** [comment]
closing as all cron jobs have been updated and can now be manually triggered

**Comment by mdickinson** [comment]
I think we're still missing this for Traits and Traits Futures.

**Comment by mdickinson** [comment]
> I think we're still missing this for Traits and Traits Futures.

enthought/traits#1480 and enthought/traits-futures#408 should fix this
